name: Prettier check

on: [push, pull_request]

jobs:
  check:
    name: Check Format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]
        node: ["18.x"]
    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v4
      - name: 🔩 Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: 🔩 Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
        env:
          COREPACK_ENABLE_STRICT: 0
      - name: 🚀 Install dependencies
        run: pnpm install
        env:
          COREPACK_ENABLE_STRICT: 0
      - name: 📦 Format project
        run: pnpm format
        env:
          COREPACK_ENABLE_STRICT: 0
      - name: 🚀 Check formatting
        run: "pnpm run format:check"
        env:
          COREPACK_ENABLE_STRICT: 0
